---

- name: Create folder for root SSH
  file:
    path="/root/.ssh"
    state="directory"
    mode="0700"

- name: Copy deploy key (read only access)
  copy:
    src='id_rsa'
    dest='/root/.ssh/id_rsa'
    mode='0600'

- name: Install git
  apt:
    name: git
    state: latest

- name: Clone application
  git:
    repo: ssh://git@github.com/dan1elhughes/fyp.git
    dest: /opt/app
    accept_hostkey: True

- name: Install packages
  npm:
    path: /opt/app

- name: Install PM2 package
  npm:
    name: pm2
    global: yes
