---

- name: Prerequisite Python installation
  become: yes
  any_errors_fatal: yes
  hosts: active
  gather_facts: no
  tags: pre
  pre_tasks:
     - name: 'Install python'
       changed_when: false
       raw: sudo apt-get -y install python-minimal

- hosts: active
  become: yes
  any_errors_fatal: yes
  roles:
  - { role: user, tags: user }
  - { role: ssh, tags: ssh }
  - { role: updates, tags: updates }
  - { role: hostname, tags: hostname }
  - { role: node, tags: node }
  - { role: app, tags: app }
