---

- name: Copy environment file
  copy:
    src='/vagrant/.env'
    dest='/opt/app/.env'

- name: Start worker process
  command: "pm2 start /opt/app/worker.js -i {{ threads }}"
  args:
    chdir: "/opt/app"
    creates: "/root/.pm2/pids/worker-0.pid"
